name: Build Driver
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # v3에서 v4로 업데이트

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2 # v1.1에서 v2로 업데이트

      - name: Build Driver
        run: |
          # 솔루션 파일(.sln) 이름을 실제 본인의 파일명으로 수정하세요
          msbuild Payson IOCTL.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Result
        uses: actions/upload-artifact@v4 # 문제의 v3를 v4로 업데이트
        with:
          name: Driver-Binary
          # 빌드 경로가 다를 수 있으니 확인이 필요합니다 (보통 x64/Release/)
          path: |
            x64/Release/*.sys
            x64/Release/*.inf
            x64/Release/*.pdb
